# Generated by Django 5.1.1 on 2024-10-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stat_calc_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
