# Generated by Django 5.1.1 on 2024-10-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stat_calc_app", "0002_customuser_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_active",
        ),
    ]
