# Generated by Django 5.1.1 on 2024-10-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stat_calc_app", "0003_remove_customuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=200, verbose_name="Пароль"),
        ),
    ]
