# Generated by Django 5.1.1 on 2024-10-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalcMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_of_data", models.IntegerField()),
                ("result", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "calc_metrics",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Calculations",
            fields=[
                ("calc_id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=30)),
                ("creation_date", models.DateTimeField()),
                ("formation_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("creator", models.CharField(max_length=50)),
                ("moderator", models.CharField(blank=True, max_length=50, null=True)),
                ("data_for_calc", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "calculations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Metrics",
            fields=[
                ("metric_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("picture_url", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "metrics",
                "managed": False,
            },
        ),
    ]
